### ISSUE TITLE
Port NaulinSolver to main BOUT++?

### ISSUE THREAD

**Issue by ZedThree** [CELMA-project/CELMA#14]
Hi Michael, some very nice work here! Some people are interested in porting the NaulinSolver into the main BOUT++ repo. Would you consider licensing it as LGPL (rather than GPL)?

**Comment by loeiten** [comment]
Sure, no problem.
I didn't realise that GPL was that restrictive, thanks for notifying.
And apologies for the code mess. I'm paying off some technical dept every now and then, but as everything else it takes longer than desired ;).
